### ISSUE TITLE
Rotate with nudge

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#101]
I feel like this would be more effective for positioning.  The slider can be used to make large rotations, but the buttons could be used to make smaller more accurate rotations.

**Comment by edvardodegaard** [comment]
For larger rotations, its still important to give the user increments that add up to 360deg on an axis. Otherwise it will be very difficult to align multiple contents or to go back-and-forth easilly.

I think we can instead keep the 45 deg, and add some rotation buttons to the nudge menu. That way the context of nudging (smaller increments) is known to the user and can simply be applied to rotation. Smaller increments to anything (position, rotation, maybe even scale in the future) = nudge.

**Comment by edvardodegaard** [comment]
Closing this due to stale, please re-open if still an issue.
