### ISSUE TITLE
Some GIFs not autoplaying

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#175]
See this room: https://megaminds.world/VhjkGmN/lets-boost-our-self-esteem

**Comment by edvardodegaard** [comment]
I cannot load the room on my 4G network atm, but judging by the network log, the files you are referring to are MP4 files, not gifs.

Autoplaying movies (mp4) is disabled at the moment until #176 is resolved, so what you are reporting is expected functionality and not a bug. 

The files were most likely added through the really old tenor system (from Hubs) that uses mp4 instead of gif files. I recommend swapping out the old gifs from "that era" with something from our new systems.
