### ISSUE TITLE
Edit Object menu not targetting the correct object

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#178]
Face Me button is no longer accurate.  It angles the object in a odd direction.
Allow students to move objects not targetting
Disable grabbing button no longer disables grabbing.

**Comment by edvardodegaard** [comment]
~~Add Auto Rotate button back to menu~~ 

Feature request added here, as its not considered a bug #183

**Comment by edvardodegaard** [comment]
From my tests this should only be happening on interactive media that has child components with special logic i.e. Video, Pdf, Audio. Needs more testing before resolving, but I beleive this is all related to setting the component on the wrong eid (child, not parent).

**Comment by edvardodegaard** [comment]
From my tests this should only be happening on interactive media that has child components with special logic i.e. Video, Pdf, Audio. Needs more testing before resolving, but I believe this is all related to setting the component on the wrong eid (child, not parent).

**Comment by edvardodegaard** [comment]
For future development reference this was due to the grabbable component being added to Audio, Video and PDF. I have added a special case for videos (You need the grabbable for menus, but I added an additional check on canMove to check the parent Interactable Media object components (where we set the locked, etc. components).
