### ISSUE TITLE
Missing defaults during migration to new permission system

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#179]
This is what I got when I entered a room.  This is the same issue we spoke about yesterday, where I entered our Stand Up Meeting room and all of the permissions were turned off somehow.  If possible, we should set all room to the same permissions they had prior to the backend switch.

![Screenshot 2023-01-17 132411](https://user-images.githubusercontent.com/111762850/212987026-68f6e740-d4b0-4f92-bf9d-f946bb1bac56.jpg)

**Comment by SpaceBeing1** [comment]
Update: I was working on the SameHere Global partner room this evening and all of the permissions were set to off

**Comment by SpaceBeing1** [comment]
Related question:  What happens if I set object permissions as allowing students to move objects, but then set room permissions to not allowing students to move objects?  Which one wins out?

**Comment by edvardodegaard** [comment]
You are right, there is an oversight with the old rooms because they have defaulted to voice / chat disabled. Ideally we should set all the "communication" to True and leave content to false, for the rooms to be similar to how they were before.

I will write a script to convert all old rooms into communication enabled rooms.

As for your question about room vs object permissions we have a general rule of thumb:
- Per-object permissions always takes precedence over per-room permissions

If the room were to override the objects, there wouldn't really be any granular control.

**Comment by edvardodegaard** [comment]
Migration has been executed on prod server and now all the old rooms have voice comm permissions.
