### ISSUE TITLE
YouTube videos don't activate until you are really close to the logo

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#186]
Could we make the activation distance the same as the Question Component?  This is how close I can get before the video pops up.

![Screenshot 2023-01-18 135009](https://user-images.githubusercontent.com/111762850/213268754-3a6c07e8-49b4-499a-9d69-24052bc2496e.jpg)

**Comment by edvardodegaard** [comment]
The activation distance should be the same as the question component, except we do not have the 50% opacity enabled for youtube videos, as its a trade-off to be able to move it around more quickly (see #185). 

I can make the distance longer, but then it will be more difficult to understand how to move it around the room, and because youtube videos with its current implementation is kinda "in-your-face", I thought this was a good distance model for now. We will do a better CSS3D implementation (where the video is actually in 3D, not just 2D with "illusion positioning" where this wont matter as much too.

**Comment by edvardodegaard** [comment]
CSS3D Implementation will improve this anyways. Closing this for now. Please reopen if the above comment is not satisfactory.
