### ISSUE TITLE
Mobile enhancements

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#193]
We will need to do a deep dive on the mobile experience and how things work.  

For instance, this is currently how YouTube videos play:

![Screenshot_20230119-100440_Chrome](https://user-images.githubusercontent.com/111762850/213478450-f0ec8ff0-8737-41d1-a265-4c4dab5a46b9.jpg)

Also, we may want to consider adding the second thumb controller button to control gaze.  At times I can accidentally interact with objects when I'm just trying to look in another direction.

**Comment by edvardodegaard** [comment]
Yes, we can have a deep dive.

Short answer to your points:

As previously mentioned, youtube videos will look and interact differently when we go from 2D projection to 3D projection.

Accidentally interacting with objects does not necessarily means the thumb controller is the best way to navigate. I think I would rather try and fix the interaction bug, for example blocking interaction when you are using dragging gestures, that could both fix your problem and keep the balance of room interaction / navigation.

**Comment by edvardodegaard** [comment]
Because your issue only contains two points, which is already talked about, I will be closing this. Please re-open or schedule a workshop if you need to do further discussion. 

As for the accidentally dragging and interacting with objects while on mobile, in my opinion we should just remove the ability to move objects on mobile, as its not a good platform nor the target for our editor / content management features. 

Follow up here #201
