### ISSUE TITLE
Add image to Link Embeds

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#213]
Just noting this.  We've discussed, and I know it is on your roadmap.

Would love to find a way to add an image to link embeds and to make them cleaner overall like you re-created for the Demo room.

![Screenshot 2023-02-06 123908](https://user-images.githubusercontent.com/111762850/217045020-385176b8-fc6c-4fc3-b8ca-ecc7aff615eb.png)

**Comment by edvardodegaard** [comment]
This was not on my roadmap, and I do not recall discussing this, other than adding a title / text above the "Open Link" button.

Users can add an image to the room and put it wherever they want. That will be the most flexible way. They can already today create exactly the layout that they want for their room and fit to the surface of their choice. I don't see why we need to enforce an image and its scale, position, etc. relative to a link object.

An "image with link" component is limiting when they can already now just place an image exactly where they want in the  scale and all other properties that they want.. Otherwise we need to create two or more components that serve the same functionality and may never be perfect for the use cases at hand.

In the future, we may have a better positioning system where you can easily place content "adjacent to" or "as a child to" another object, to make their position linked etc. Then we can look into how to combine different types of media together to create nice layouts. Until then in my opinion we don't need to add a custom "link with image" component.

Another way to go with a new system would be to assign a "clickable" component to an image, 3D model, or anything else, that will convert a normal image into a clickable link, much like the images on websites and articles etc. all around the web today. Follow that here #219 


I will close this as wontfix, but feel free to re-open or put it on agenda for next meeting if you want to discuss it further.

**Comment by SpaceBeing1** [comment]
An image may not be neccessary, as the way Hubs currently does it is not ideal either.  I think adding a title / text above the Open Link button will do the trick.  

My goal here is to make links appear more streamlined.  Right now, this is the result if you have long URLs.  Could we limit the length of the url so it fits on one line?  Or perhaps not even have one so it's just Title / text and the open link button?

![Screenshot 2023-02-09 093417](https://user-images.githubusercontent.com/111762850/217843854-6064bb36-b70c-4a47-981e-27249cf355ab.png)
