### ISSUE TITLE
Add Double Click to bring up Object Menu

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#217]
I am aware that this is the less accessible option.  Nevertheless, I have encountered teacher who do not know how to right click an object.  I've even been on their MacBooks that don't even seem to have the option enabled.

My suggestion is to have BOTH actions open up the Object Menu.  That way it will be accessible by the most users.

**Comment by edvardodegaard** [comment]
CTRL + Click or Two-finger click is the official and documented way to do secondary context menu actions in Mac OS. That is the standard in every website and interface made for Mac. If the users you are describing are using any software, such as Photoshop, or want to copy a link on a website, what do they actually do if they cant control+click or two-finger tap?

Implementing double clicking in 3D space would require us to rewrite a big chunk of the interaction system and will not currently be possible without considerable development time. I don't see why we need to do this when we have CTRL + Click for Mac indicated in the hint menu on the bottom right corner.

I will propose an alternative to have a button on the keyboard to bring up the object menu while hovering, such as "E" for "Edit" or "O" for "Object Menu". That way we provide an alternative for mouse input altogether instead of doubling down on one input method that can be wonky and is generally poor for accessibility. A mouse-over + keypress would be accessible and inclusive to different sorts of devices - even without mouse input at all. In the future it can be extended to allow users to only use their keyboard for all aspects of the program. Mouse cursors are simply not a good way to deal with user input if you want it to be accessible. 

Please track future progress on this issue here #218
