### ISSUE TITLE
Accessible way to bring up object menu

### ISSUE THREAD

**Issue by edvardodegaard** [gomegaminds/hubs#218]
See discussion from #217 

This will provide an alternative way that is not cursor-centric and more accessible than using mouse to bring up the object menu. We can test different implementations such as "nearest object" or selecting objects by keybaord, or on cursor-hovering.

**Comment by SpaceBeing1** [comment]
I like this solution.  The reason I keep seeking an alternative to the right click is because double-click is the defacto method for opening up menus for pretty much anyone over 40, and especially Mac users over 40.  Most don't even know what a right click is!  And unfortunately, they make up a large percentage of our potential users.  The issue came up again recently when I was trying to do a demo on one of our pilot teacher's laptops and I was unable to right click.  Two finger click and Control click also were not working for whatever reason.

**Comment by edvardodegaard** [comment]
On the agenda for todays meeting!
