### ISSUE TITLE
For Discussion: should content that's placed automatically have "Disable Grabbing" checked?

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#229]
From a UX perspective, if I am creating a Presentation Room, it's frustrating to complete a room then realize I have to go back to every single object and click Disable Grabbing.  

Perhaps we should disable grabbing as default, then if the teacher wants to leave a 3D object as a manipulative or something, they can individually select that object and click "Allow this object to be moved"

**Comment by edvardodegaard** [comment]
Good question. 

When I implemented this, I decided to leave it unchecked for the following reasons:
- Only the teacher can grab / move stuff inside a teacher focused room, so guests will not be able to accidentally drag stuff
- Teacher may want to move stuff right away and we should not make more obstacles than needed for them to do that

One idea I have that can be kind of interesting to explore that I think could solve the issue you are describing and improve UX:

**Rename "Classroom Editor" to "Edit Mode" and let Edit Mode determine if a user can move content.** 

This would create a strong separation of functionality and make it less confusing with all the checkboxes and locking content imo.

- When inside Edit Mode, you can move **everything** except:
  - Objects that are locked (disable accidental grabbing checkbox)
- When outside Edit Mode, you can **not move anything** except:
  - Your own Sticky Note and Webcams
  - Objects that have "Students can move" checkbox toggled

- A nice side-effect is that the teacher can view the room as a student when outside of Edit Mode.


This would allow the flexibility in the following scenarios:
- For teacher rooms, the teacher can present and look at their room without accidentally grabbing something
- For teacher rooms, the students cannot move stuff by default, unless the teacher overrides the permissions, for example making an object moveable instead of locking everything else.
- For student created rooms, visitors and even teacher (even though teacher owns the room) cannot move stuff unless inside edit mode, which is generally a nice thing.
- From the dashboard we can remove "Classroom Editor" as we have a stronger terminology and concept to implement switching between modes.
  - In the onboarding we can then start the onboarding with navigation, communication ,etc. before going into edit mode

**Comment by edvardodegaard** [comment]
Ref discord, we will be testing the aforementioned approach of Edit mode.
