### ISSUE TITLE
Add Troika Text Button to Student and Teacher UIs

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#49]
Can we implement this to the main UIs?  I would love to have it available to demo to teachers tomorrow at the AMA Session.

**Comment by camelgod** [comment]
I think we discussed not having it because we want to emphasize the "creation" functionality in the Classroom to make strong seperation from Session and Classroom.

We need to figure a smooth way to place it in the UI. Right now there are no "creation" tools in the normal session UI. Let me think a little.

**Comment by SpaceBeing1** [comment]
Hmmm... I think you're right.  It's stronger as a feature only in the Classroom Editor. That said, students and teachers will need a way to communicate with text, so perhaps we can add a sticky note button?

**Comment by camelgod** [comment]
> Hmmm... I think you're right. It's stronger as a feature only in the Classroom Editor. That said, students and teachers will need a way to communicate with text, so perhaps we can add a sticky note button?



Alright, If we are changing scope, please create a new issue. It will be helpful to know more about what you mean with "need a way to communicate with text". They have chat already. If sticky notes are really needed in a session, or covered by other elements such as text submissions, etc. we can discuss it in new issue :) 
Thank you!
