### ISSUE TITLE
Some objects do not appear or are positioned incorrectly when returning to the classroom editor.

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#99]
Some objects disappear entirely
Some objects seem to be resized
Some objects are also not placed where they were.

This could be related to the scale slider.  All of the objects where this occurred were resized by the slider.  

Also, sometimes the object would dissapear, but later, when I returned it would be back.  So the results were inconsistent.

**Comment by edvardodegaard** [comment]
I am unable to reproduce this.

Can you please provide step by step instructions to reproduce this?

Also please check that its not in related to logging in / out from different accounts and room permissions.

**Comment by edvardodegaard** [comment]
It is not related to the scale slider, but to the way Sketchfab objects are very vast and varied. Hubs sometimes fails at figuring out how to scale the object based on bones, animation, node trees, child objects, etc. 

Need to figure out a clean way to import from Sketchfab, but this is a deeper discussion because Sketchfab is overall not an ideal integration in terms of network capcity, filesizes, mobile compatibility, and the tons of weird and buggy objects available there.

**Comment by edvardodegaard** [comment]
I discovered a race condition in the function that executes when the model is alledgedly loaded. However some sketchfab models will trigger this function before being loaded fully (resulting in the scaling logic not being able to apply on the non-existent mesh). 

Added a 350 ms delay on loading to capture the edge case where a sketchfab model is loading too quickly.

**Comment by edvardodegaard** [comment]
There are two seperate problems / race conditions, one from sketchfab and another from gltf-model-plus updates.

1. The Aframe model-loaded event is usually sent once with the correct position. However sometimes two model-loaded events are sent, the first one with a Vector3(0.001, 0.001, 0.001) scaling, while the other will have the correct scale. However the eventListener is set to { once: true } and only the first and incorrect one will be triggered, leaving the last and correct one to fall on deaf ears.

I have set once: false because the correct scale always comes after the first one (I think it tries to re-load / update from gltf-model-plus if it fails first time, but I cannot seem to trace the original emit statement)

This workaround solves the issue for now. Later on we will redefine how models are imported in general, so this will be sufficient for now.

3. In addition, sometimes immediatley loading assets from sketchfab will try to scale the object faster than the object can load, leading to a missing mesh and incorrect scale (because scaling cannot be applied if a mesh does not exist). I have added a 500 ms delay on the model-loaded event to account for this, which works consistently for now.
